twitter:
    name: 'chris_garvin'
    consumer_key: '3TtaVtWhDftYm1wthw4jPatvs'
    consumer_secret: 'DsqiwQODjVnXdi47i5FoQTux9Cj3UeKJg7xq6UlESXbHPDVmy1'
    oauth_token: '14592857-uvxGJ5MVegYkpNNRL4rq61TX4hoRPWBVAtWf6XWd5'
    oauth_token_secret:'JnVCQOmBHMUV4IkDcYx7TvDL3a41UvtFqcUG5yqsBWTM7'
